Cadastro agenda
arthurlima96/nosso-calendario-rep pull request #3
Opened 2020-01-23 22:29 UTC by arthurlima96

Implementação da funcionalidade de criação de uma nova agenda no momento do cadastro do usuário

2020-01-23 23:52 UTC, asouza requested changes

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/model/User.java
>  	public void setLogin(String login) {
Acho que sobrou um setLogin aqui. Não temos edição parcial do usuário ainda.

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/AgendaForm.java
> +	@NotNull(message = " O nome não pode ser nulo")
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*
Aqui da para usar @NotBlank. Ele já pega os dois :).

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/model/User.java
> +	public User(@NotBlank @NotEmpty @Email String login,EncodeSenha senha,@NotBlank @NotEmpty String nome) {
*Usamos tudo que conhecemos que está pronto. Só fazemos código do zero se for estritamente necessário.*

NotBlank já faz o que o NotEmpty faz :).

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.saveAll(userForm.novasAgendas(user));
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Aqui temos o seguinte:
* um novo método para criar agenda no form
* Um atributo do tipo Form novo no UserForm linkando com a Agenda
* E o par de getter e setter para o form da agenda. 

A questão é que a gente não tem um formulário para criação de agenda ainda... 

Como você poderia fazer esse código sem mexer em nada no UserForm e também sem criar a AgendaForm. 
Lembra que você também cria apenas uma agenda na hora do cadastro.

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.saveAll(userForm.novasAgendas(user));
E neste momento você também tem apenas uma possibilidade de criação de agenda, que é em função do novo usuário. Não é para ter possibilidade de criar uma agenda nova com um nome diferente do usuário que está se cadastrando.

2020-01-23 23:52 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/model/Agenda.java
> +	public Long getId() {
*dealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Precisamos de todos esses getters aqui?

2020-01-24 00:17 UTC, arthurlima96 commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.saveAll(userForm.novasAgendas(user));
Fiquei na duvida com relação a descrição da agenda, eu passaria ela como um atributo de UserForm ?
Já o objeto AgendaForm não existiria mais

2020-01-24 00:23 UTC, arthurlima96 commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.saveAll(userForm.novasAgendas(user));
A descrição da agenda deve ser passada na chamada da API ?

2020-01-24 00:43 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.saveAll(userForm.novasAgendas(user));
Ótima pergunta, inclusive alterei no cartão :). A descrição da agenda também é padrão neste momento. Coloquei lá que deve ser "Agenda {nomeDoUsuario}" onde o {nomoDoUsuario} é o usuário criador da agenda.

2020-01-24 01:56 UTC, asouza requested changes
O código está ótimo! Só adicionei mais um desafio de restrição em relação ao a criação da Agenda. Para que, neste momento, realmente não seja possível criar uma agenda diferente do combinado.

2020-01-24 01:56 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/rest/UserController.java
> +		agendaRepository.save(new Agenda(user.getNome(), "Agenda do(a) "+user.getNome(), user));
Boa! Mas olha só: do jeito que está, eu ainda posso criar uma Agenda com o nome e descrição diferente do combinado. Quanto mais controle você tiver do código, melhor. Como fazer para *garantir*, neste momento, que a agenda seja criada exatamente igual ao que você colocou aí?

2020-01-24 09:03 UTC, asouza approved these changes
Boa! Fechou aqui! Este tipo de restrição ajuda bastante quando outra pessoa vai pegar para manter o código. Ela tem menos coisa para descobrir. Só deixei um comentário para, talvez, gerar uma reflexão.

2020-01-24 09:03 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/model/Agenda.java
> +		this.setNome(user.getNome());
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*
+
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho.*

Toda indireção que você coloca no código aumenta o número de coisas que a pessoa precisa saber. Por isso que temos que ir pesando sempre. Aqui está simples e você deixou como método privado. A pergunta que fica é: pq ```setNome``` é de alguma forma mais interessante do que ```this.nome = nome?```

2020-01-24 09:03 UTC, asouza commented on nosso-calendario/src/main/java/com/br/devefc/nossocalendario/model/Agenda.java
> +		this.setNome(user.getNome());
E existe uma boa chance do método setDescricao virar público e manter aquela concatenação ali, o que, provavelmente, geraria um bugzinho.

2020-01-24 11:43 UTC, merged